name = "hogflare"
main = "build/index.js"
compatibility_date = "2025-01-09"

[observability]
enabled = true

[vars]
CLOUDFLARE_PIPELINE_ENDPOINT = "https://dfbc2951bd3c4d299c37356ff8c02908.ingest.cloudflare.com"
CLOUDFLARE_PIPELINE_TIMEOUT_SECS = "10"

[build]
command = "cargo install worker-build@^0.7 && worker-build --release"
